name: test-coverage
on: push
jobs:
  test_report:
    name: yarn install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: yarn install
      uses: docker://node:12.14.0
      with:
        entrypoint: yarn
        args: install

    - name: yarn test
      uses: docker://node:12.14.0
      with:
        entrypoint: yarn
        args: run test

    - name: test coverage
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: coverage-report/clover.xml
        flags: unittests
